import { FormEvent, useEffect, useState } from 'react'
import * as api from './api'

const stages = ['PLANNING','INVESTIGATING','KNOWLEDGE_LOOKUP','DIAGNOSING','CRITIC_REVIEW','EVIDENCE_COLLECTED','POLICY_CHECK','AWAITING_APPROVAL','EXECUTING','VERIFYING','REPAIRED']
export function App() {
  const [message,setMessage]=useState('调查订单 O1001 的支付和库存链路'),[orderId,setOrderId]=useState('O1001'),[run,setRun]=useState<api.Run>(),[events,setEvents]=useState<api.TimelineEvent[]>([]),[steps,setSteps]=useState<api.Step[]>([]),[evidence,setEvidence]=useState<api.Evidence[]>([]),[error,setError]=useState(''),[sku,setSku]=useState('SKU1'),[qty,setQty]=useState(1),[key,setKey]=useState('repair-'+Date.now())
  const refresh=async()=>{if(!run)return;try{const [r,s,e]=await Promise.all([api.getRun(run.run_id),api.getSteps(run.run_id),api.getEvidence(run.run_id)]);setRun(r);setSteps(s.steps);setEvidence(e.evidence)}catch(e){setError((e as Error).message)}}
  useEffect(()=>{if(!run)return;const stop=api.subscribe(run.run_id,e=>{setEvents(x=>[...x,e]);refresh()});return stop},[run?.run_id])
  const start=async(e:FormEvent)=>{e.preventDefault();setError('');try{const r=await api.createInvestigation(message,orderId);setRun(r);setEvents([]);setSteps([]);setEvidence([])}catch(e){setError((e as Error).message)}}
  const approve=async()=>{if(!run)return;try{setRun(await api.approveRun(run.run_id));await refresh()}catch(e){setError((e as Error).message)}}
  const execute=async()=>{if(!run)return;try{setRun(await api.executeRun(run.run_id,[{sku_id:sku,quantity:qty}],key));await refresh()}catch(e){setError((e as Error).message)}}
  const diagnosis=run?.final_summary?.diagnosis
  return <><header><div className="brand"><span className="mark">OG</span><div><strong>OrderGuard</strong><small>incident control room</small></div></div><span className="online"><i/>runtime connected</span></header><main><section className="hero"><div><p className="eyebrow">ORDER INVESTIGATION</p><h1>Trace the break.<br/><em>Protect the fix.</em></h1><p className="lede">沿着订单、支付、库存和事件流的证据链，定位异常并验证修复。</p></div><form onSubmit={start}><label>调查问题</label><textarea value={message} onChange={e=>setMessage(e.target.value)}/><label>订单号</label><input value={orderId} onChange={e=>setOrderId(e.target.value)}/><button>开始调查 <b>↗</b></button></form></section>{error&&<div className="error">{error}</div>}{run&&<section className="workspace"><div className="runbar"><code>{run.run_id}</code><span className="state">{run.status}</span><button className="quiet" onClick={refresh}>刷新</button></div><div className="stagebar">{stages.map(s=><span className={stages.indexOf(s)<=stages.indexOf(run.status)?'done':''} key={s}>{s}</span>)}</div><div className="columns"><article className="panel"><div className="paneltitle"><h2>Live timeline</h2><small>{events.length} events</small></div>{events.length?events.map((e,i)=><div className="event" key={i}><time>{new Date(e.created_at||'').toLocaleTimeString()}</time><div><b>{e.type}</b><code>{JSON.stringify(e.payload)}</code></div></div>):<p className="muted">等待 Agent 事件...</p>}</article><article className="panel"><div className="paneltitle"><h2>Diagnosis</h2>{diagnosis&&<span className="confidence">{Math.round(diagnosis.confidence*100)}%</span>}</div>{diagnosis?<><h3 className="cause">{diagnosis.root_cause}</h3><p className="muted">证据：{diagnosis.evidence_ids.join(', ')}</p>{diagnosis.recommended_action&&<span className="tag">{diagnosis.recommended_action}</span>}</>:<p className="muted">等待 Diagnosis Agent 输出...</p>}{run.status==='EVIDENCE_COLLECTED'&&<button className="action" onClick={approve}>通过策略检查</button>}{run.status==='AWAITING_APPROVAL'&&<div className="repair"><h3>Execute repair</h3><div className="row"><input value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU ID"/><input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></div><input value={key} onChange={e=>setKey(e.target.value)} placeholder="幂等键"/><button className="action" onClick={execute}>执行并验证</button></div>}</article></div><div className="columns"><article className="panel"><div className="paneltitle"><h2>Agent steps</h2></div>{steps.map(s=><div className="tableRow" key={s.step_id}><b>{s.agent_type}</b><span>{s.status}</span><small>{s.error_code||''}</small></div>)}</article><article className="panel"><div className="paneltitle"><h2>Evidence chain</h2></div>{evidence.map(x=><div className="evidence" key={x.evidence_id}><b>{x.tool_name}</b><span>{x.source}</span><code>{x.evidence_id}</code></div>)}</article></div></section>}</main></>
}
